fix: only show error message when command is set to not exit if error (#6)

diff --git a/vpn b/vpn
--- a/vpn
+++ b/vpn
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
 
-set -eE -o functrace
+set -eE
 failure() {
   local lineno=$1; local msg=$2
-  echo "$(basename "$0"): failed at $lineno: $msg"
+  [[ "$-" =~ .*e.* ]] && echo "$(basename "$0"): failed at $lineno: $msg"
 }
 trap 'failure ${LINENO} "$BASH_COMMAND"' ERR
 
